plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fanorisky.pinebrowser'
    compileSdk 36

    defaultConfig {
        applicationId 'com.fanorisky.pinebrowser'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.browser:browser:1.10.0'
    implementation 'androidx.webkit:webkit:1.17.0'
}
